title: Daniel Soliman's Blog
author: Daniel Soliman
email: dasoliman@ebnet.org
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I am a junior in EBHS writing this blog for my AP Computer Science Principles class. 

# social links
twitter_username: banned :(
github_username:  dansolo12

show_excerpts: true # set to false to remove excerpts on the homepage
